# Generated by Django 5.2.7 on 2025-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='yo_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='yo_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='yo_transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='provider',
            field=models.CharField(choices=[('yo', 'Yo! Payments'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('yo', 'Yo! Payments'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=10),
        ),
    ]
