# Generated by Django 5.2.7 on 2025-10-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['branch', 'employee_type', 'user__first_name']},
        ),
    ]




