# Generated by Django 5.2.7 on 2025-10-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date', '-reservation_time']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_number']},
        ),
    ]




