# Generated by Django 5.2.7 on 2025-10-22 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_options'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('branch', 'ingredient')},
        ),
    ]




