# Generated by Django 5.2.7 on 2025-10-22 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_options_stock_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_source',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a food source that determines the price', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.foodsource'),
        ),
    ]
