# Generated by Django 5.2.7 on 2025-10-22 21:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_foodsource_alter_menuitem_price_menuitem_food_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='pricing_type',
            field=models.CharField(choices=[('direct', 'Direct Price'), ('source', 'Food Source Price'), ('free', 'Free (Base Item)')], default='direct', help_text='How should this item be priced?', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='food_source',
            field=models.ForeignKey(blank=True, help_text="Food source that determines price (use when pricing type is 'Food Source Price')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.foodsource'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Direct price (use when pricing type is 'Direct Price')", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
