# Generated by Django 5.2.7 on 2025-10-23 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitem_pricing_type_alter_menuitem_food_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='food_source',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='base_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'base'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_as_base', to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='compatible_sources',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_type': 'source'}, related_name='compatible_bases', to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('base', 'Base Food'), ('source', 'Protein Source'), ('combo', 'Complete Meal'), ('beverage', 'Beverage'), ('side', 'Side Dish')], default='combo', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein_source',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'source'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_as_source', to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='pricing_type',
            field=models.CharField(choices=[('direct', 'Direct Price'), ('base', 'Base Item (Requires Source)'), ('source', 'Protein Source'), ('combo', 'Pre-defined Combo')], default='direct', max_length=10),
        ),
    ]
