# Generated by Django 5.2.7 on 2025-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_menuitem_food_source_menuitem_base_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='compatible_sources',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_type': 'source'}, to='inventory.menuitem'),
        ),
    ]




