# Generated by Django 5.2.7 on 2025-10-27 20:48

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_menuitem_compatible_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='base_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_as_base', to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='compatible_sources',
            field=models.ManyToManyField(blank=True, to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for this menu item', null=True, upload_to=inventory.models.menu_item_image_path),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='protein_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_as_source', to='inventory.menuitem'),
        ),
    ]




