# Generated by Django 5.2.7 on 2025-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_menuitem_options_alter_menuitem_base_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='base_category',
            field=models.CharField(blank=True, choices=[('free', 'Free Base Food'), ('premium', 'Premium Base Food')], help_text='Only for base items - indicates if base is free or premium', max_length=10, null=True),
        ),
    ]
