# Generated by Django 5.2.7 on 2025-10-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_menuitem_food_source_menuitem_base_item_and_more'),
        ('orders', '0002_alter_order_customer_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_base_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'base'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_base_orders', to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_protein_source',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'source'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_source_orders', to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_custom_combo',
            field=models.BooleanField(default=False),
        ),
    ]




