# Generated by Django 5.2.7 on 2025-11-01 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='html_template',
            field=models.TextField(blank=True, help_text='HTML version for email notifications', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]




