# Generated by Django 5.2.7 on 2025-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('reservation_confirm', 'Reservation Confirmation'), ('order_ready', 'Order Ready'), ('order_preparing', 'Order Preparing'), ('order_served', 'Order Served'), ('table_ready', 'Table Ready'), ('payment_confirm', 'Payment Confirmation'), ('low_stock_alert', 'Low Stock Alert'), ('system_alert', 'System Alert')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='sms_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject_template',
            field=models.CharField(max_length=255),
        ),
    ]




